### ISSUE TITLE
Move config to $XDG_CONFIG_HOME..

### ISSUE THREAD

**Issue by necauqua** [nikochiko/autosaved#5]
.. which defaults to `$HOME/.config`.

How are you making a new app IN 2022(!) and yet make this mistake of supporting the pollution of the home folder with endless dotfiles is beyond me

Great app though, I was brought here by those google suggestions at new tab

**Comment by nikochiko** [comment]
Hey @necauqua thanks for the compliment. Also thanks for being the first one besides me to create an issue! :tada:

I built this over a weekend-hackathon, so I just went with the fastest way to get it setup. I agree with you that we shouldn't put more stuff into the $HOME directory.

Would you like to contribute this part?

**Comment by necauqua** [comment]
> Would you like to contribute this part?

Whoops, totally forgot I made this issue - it was from my phone while being half-asleep heh :)
